#include "kiero.hpp"
#include "kiero_vulkan.hpp"
#include "kiero_intern.hpp"

static const char* const k_vk_methods[] = {
  "vkCreateInstance",
  "vkDestroyInstance",
  "vkEnumeratePhysicalDevices",
  "vkGetPhysicalDeviceFeatures",
  "vkGetPhysicalDeviceFormatProperties",
  "vkGetPhysicalDeviceImageFormatProperties",
  "vkGetPhysicalDeviceProperties",
  "vkGetPhysicalDeviceQueueFamilyProperties",
  "vkGetPhysicalDeviceMemoryProperties",
  "vkGetInstanceProcAddr",
  "vkGetDeviceProcAddr",
  "vkCreateDevice",
  "vkDestroyDevice",
  "vkEnumerateInstanceExtensionProperties",
  "vkEnumerateDeviceExtensionProperties",
  "vkEnumerateDeviceLayerProperties",
  "vkGetDeviceQueue",
  "vkQueueSubmit",
  "vkQueueWaitIdle",
  "vkDeviceWaitIdle",
  "vkAllocateMemory",
  "vkFreeMemory",
  "vkMapMemory",
  "vkUnmapMemory",
  "vkFlushMappedMemoryRanges",
  "vkInvalidateMappedMemoryRanges",
  "vkGetDeviceMemoryCommitment",
  "vkBindBufferMemory",
  "vkBindImageMemory",
  "vkGetBufferMemoryRequirements",
  "vkGetImageMemoryRequirements",
  "vkGetImageSparseMemoryRequirements",
  "vkGetPhysicalDeviceSparseImageFormatProperties",
  "vkQueueBindSparse",
  "vkCreateFence",
  "vkDestroyFence",
  "vkResetFences",
  "vkGetFenceStatus",
  "vkWaitForFences",
  "vkCreateSemaphore",
  "vkDestroySemaphore",
  "vkCreateEvent",
  "vkDestroyEvent",
  "vkGetEventStatus",
  "vkSetEvent",
  "vkResetEvent",
  "vkCreateQueryPool",
  "vkDestroyQueryPool",
  "vkGetQueryPoolResults",
  "vkCreateBuffer",
  "vkDestroyBuffer",
  "vkCreateBufferView",
  "vkDestroyBufferView",
  "vkCreateImage",
  "vkDestroyImage",
  "vkGetImageSubresourceLayout",
  "vkCreateImageView",
  "vkDestroyImageView",
  "vkCreateShaderModule",
  "vkDestroyShaderModule",
  "vkCreatePipelineCache",
  "vkDestroyPipelineCache",
  "vkGetPipelineCacheData",
  "vkMergePipelineCaches",
  "vkCreateGraphicsPipelines",
  "vkCreateComputePipelines",
  "vkDestroyPipeline",
  "vkCreatePipelineLayout",
  "vkDestroyPipelineLayout",
  "vkCreateSampler",
  "vkDestroySampler",
  "vkCreateDescriptorSetLayout",
  "vkDestroyDescriptorSetLayout",
  "vkCreateDescriptorPool",
  "vkDestroyDescriptorPool",
  "vkResetDescriptorPool",
  "vkAllocateDescriptorSets",
  "vkFreeDescriptorSets",
  "vkUpdateDescriptorSets",
  "vkCreateFramebuffer",
  "vkDestroyFramebuffer",
  "vkCreateRenderPass",
  "vkDestroyRenderPass",
  "vkGetRenderAreaGranularity",
  "vkCreateCommandPool",
  "vkDestroyCommandPool",
  "vkResetCommandPool",
  "vkAllocateCommandBuffers",
  "vkFreeCommandBuffers",
  "vkBeginCommandBuffer",
  "vkEndCommandBuffer",
  "vkResetCommandBuffer",
  "vkCmdBindPipeline",
  "vkCmdSetViewport",
  "vkCmdSetScissor",
  "vkCmdSetLineWidth",
  "vkCmdSetDepthBias",
  "vkCmdSetBlendConstants",
  "vkCmdSetDepthBounds",
  "vkCmdSetStencilCompareMask",
  "vkCmdSetStencilWriteMask",
  "vkCmdSetStencilReference",
  "vkCmdBindDescriptorSets",
  "vkCmdBindIndexBuffer",
  "vkCmdBindVertexBuffers",
  "vkCmdDraw",
  "vkCmdDrawIndexed",
  "vkCmdDrawIndirect",
  "vkCmdDrawIndexedIndirect",
  "vkCmdDispatch",
  "vkCmdDispatchIndirect",
  "vkCmdCopyBuffer",
  "vkCmdCopyImage",
  "vkCmdBlitImage",
  "vkCmdCopyBufferToImage",
  "vkCmdCopyImageToBuffer",
  "vkCmdUpdateBuffer",
  "vkCmdFillBuffer",
  "vkCmdClearColorImage",
  "vkCmdClearDepthStencilImage",
  "vkCmdClearAttachments",
  "vkCmdResolveImage",
  "vkCmdSetEvent",
  "vkCmdResetEvent",
  "vkCmdWaitEvents",
  "vkCmdPipelineBarrier",
  "vkCmdBeginQuery",
  "vkCmdEndQuery",
  "vkCmdResetQueryPool",
  "vkCmdWriteTimestamp",
  "vkCmdCopyQueryPoolResults",
  "vkCmdPushConstants",
  "vkCmdBeginRenderPass",
  "vkCmdNextSubpass",
  "vkCmdEndRenderPass",
  "vkCmdExecuteCommands",
};

template <>
kiero::Error kiero::locate<kiero::Implementation_Vulkan>(void* in, void* out)
{
#ifdef KIERO_ON_WINDOWS
  KIERO_UNUSED(in);

  auto vulkan_dll = GetModuleHandleA("vulkan-1.dll");
  if (!vulkan_dll) {
    KIERO_DBG_MSG("vulkan-1.dll not loaded");
    return Error_ModuleNotFound;
  }

  VulkanOutput* output = (VulkanOutput*)out;

  for (auto name : k_vk_methods) {
    auto ptr = (void*)GetProcAddress(vulkan_dll, name);
    output->methods[name] = ptr;
  }
#else
# error "Not implemented yet"
#endif

  return Error_Nil;
}
